### ISSUE TITLE
[Feature Request] Allow customized game launch path

### ISSUE THREAD

**Issue by KrisCris** [soulsmods/ModEngine2#55]
This would make it possible to directly launch custom launchers like the one for elden ring seamless coop mod. https://www.nexusmods.com/eldenring/mods/510?tab=description

**Comment by garyttierney** [comment]
ModEngine needs to be in control of creating the game process for injection to work, so making this work is tricky. However, Seamless Coop only requires an external DLL to be loaded. You can do that by editing your modengine configuration like this:
```toml
[modengine]
external_dll_discovery = true
external_dlls = ["elden_ring_seamless_coop.dll"]
```

Leaving this open as a tracker for UX of using external launchers.
