### ISSUE TITLE
compatibility under Steam deck 

### ISSUE THREAD

**Issue by Kusanagi942** [soulsmods/ModEngine2#58]
hello, does someone knows how to make work mod engine 2 under steam deck (linux) .when i launch the file .exe by using proton/wine, i only have a black command screen popping up then disappears then nothing. Trying to resolve that since several days, thank you !

**Comment by Cloudef** [comment]
Workaround: https://github.com/Cloudef/ModEngine2/releases/tag/2.0.0.1-proton

**Comment by Kusanagi942** [comment]
> Workaround: https://github.com/Cloudef/ModEngine2/releases/tag/2.0.0.1-proton-v2

Thank you ! actually i did every steps you wrote but when i launch the game, the mods are not working (but anti cheat seems disable)

I would like to make work Elden ring reforged and seamless coop. I can run seamless by launching the seamlesscoop.exe but cant make work Grand merchant or Elden ring reforged through Elden mod loader...

thank you...

**Comment by Kusanagi942** [comment]
these are my files

![290117334_396384502516518_6271501805134120021_n](https://user-images.githubusercontent.com/106956327/175720634-0b5af77b-9dc2-4e3c-a011-06cd95f44aef.jpg)
![289739566_706676460402719_8017171617487060664_n](https://user-images.githubusercontent.com/106956327/175720636-7083a380-07e3-47d2-90e7-f2789fa485d1.jpg)
![290172269_1113988466127462_2327222850239276753_n](https://user-images.githubusercontent.com/106956327/175720638-dea6858c-0e03-4ddf-a21e-89c4b29ba8e9.jpg)
![289155380_1490581111397072_2573909565384156771_n](https://user-images.githubusercontent.com/106956327/175720639-b3c430bb-cc33-4e2a-9929-b0ac5ab768f8.jpg)

**Comment by Cloudef** [comment]
Only put dll files in the mods folder. The SeamlessCoop folder with the .ini file needs to be in the Game folder. "randomizer" folder needs to also be in the Game folder.

**Comment by Cloudef** [comment]
Example how my directory structure looks for randomizer mod:
```
ELDEN RING
└── Game
    ├── SeamlessCoop
    │   └── cooppassword.ini
    ├── mods
    │   ├── lua.dll
    │   ├── modengine2.dll
    │   └── seamless_coop.dll
    ├── movie
    ├── randomizer
    │   ├── diste
    │   ├── event
    │   ├── map
    │   ├── msg
    │   ├── script
    │   ├── sfx
    │   ├── spoiler_logs
    │   ├── 12784.randomizeopt
    │   ├── EldenRingRandomizer.exe
    │   ├── README.txt
    │   ├── config_eldenringrandomizer.toml
    │   ├── locations.txt
    │   ├── oo2core_6_win64.dll
    │   └── regulation.bin
    ├── sd
    ├── amd_ags_x64.dll
    ├── bink2w64.dll
    ├── dinput8.dll
    ├── eldenring.exe
    ├── eossdk-win64-shipping.dll
    ├── eossdk-win64-shipping.so
    ├── mod_loader_config.ini
    ├── modengine.toml
    ├── oo2core_6_win64.dll
    ├── regulation.bin
    ├── start_protected_game.exe
    └── steam_api64.dll
 ```

**Comment by Kusanagi942** [comment]
> Only put dll files in the mods folder. The SeamlessCoop folder with the .ini file needs to be in the Game folder. "randomizer" folder needs to also be in the Game folder. Also you must have modengine.toml in your game folder.
> 
> Edit: I haven't tested with reforged. But it should be similar to randomizer. Put reforged files in own folder in the game directory, and in the modengine.toml change the `path = "randomizer"` part to `path = "reforged"`, or whatever folder name you used for the reforged files.

Thank you for taking time to help me, i appreciate a lot.

Actually i deleted everything in my Game file like Easy anti cheat folder. I only kept "Data" files. My actual problem is, that i dont have the file "modengine.toml" and dont know where to get it.

it should works by launcher the eldenring.exe right? (and i also did the launch options like you told)

here's my tree 
![290131269_464134212208149_9008289645534007996_n](https://user-images.githubusercontent.com/106956327/175764366-04096ef0-71bd-4f7d-a264-4b231724382e.jpg)
![289969936_1043832826262770_3893800411691609463_n](https://user-images.githubusercontent.com/106956327/175764367-f91cf1b4-f728-4cac-9e20-e4ae5b2bfe30.jpg)
![289584776_739634607237757_4449426657697224856_n](https://user-images.githubusercontent.com/106956327/175764368-4e16024d-c917-4ceb-9e7b-c57a81f28954.jpg)

Thank you so much.

**Comment by Cloudef** [comment]
modengine.toml is just the same file as config_eldenring.toml or so on.
Something like this should work for you:
```toml
# Global mod engine configuration
[modengine]
# If set to true the debug console will appear while the game is running
debug = false

# Mod loader configuration
[extension.mod_loader]
enabled = true

# Not currently supported for Elden Ring
loose_params = false

# List of directories that contain modded files in order of prioritization. Inside each specified mod directory must have the game
# assets in Fromsoft's asset structure. I.e. if you mod parts/something.partsbnd.dcx, the modded version must be at mod/parts/something.partsbnd.dcx.
# Absolute paths to mods are supported but must use '\\' to separate path items. For example, if your mod is at E:\coolstuff\coolmod, you must enter
# the path in the config as "E:\\coolstuff\\coolmod".
# If there's no drive specifier (C:, D:, etc), the path is relative to where the launcher is located. For example, having the path as "mod" will tell
# modengine 2 to look for the directory mod inside the mod engine 2 directory with the launcher.
#
# Multiple mods must be separated with commas. For example if you have 3 mods, you will have something like the following:
# mods = [
#    { enabled = true, name = "coolmod", path = "mod1" },
#    { enabled = true, name = "nicemod", path = "mod2" },
#    { enabled = true, name = "sosomod", path = "mod3" }
# ]
# Note that modengine 2 currently has no way to resolve conflicting files including regulation.bin, and thus the mod with the highest priority
# will have the modded file be loaded in the case of conflict. Some support for merging of params and potentially other assets is considered for
# a future release.
mods = [
    { enabled = true, name = "default", path = "Reforged" }
]

# When enabled, scylly hide will be injected into the game. This allows for antidebug measures in the game to be bypassed so that you can attach
# debuggers such as Cheat Engine, x64dbg, windbg, etc to the game without as much trouble. If you're not reverse engineering the game, this option
# is probably not for you.
[extension.scylla_hide]
enabled = false
```
